networks:
    avsnet:
        driver: bridge

services:
    openrank-node-computer:
        build:
            context: .
            dockerfile: node/Dockerfile.node-computer
        container_name: openrank-node-computer
        network_mode: host
        env_file:
            - .env
        restart: unless-stopped

    openrank-node-challenger:
        build:
            context: .
            dockerfile: node/Dockerfile.node-challenger
        container_name: openrank-node-challenger
        network_mode: host
        env_file:
            - .env
        restart: unless-stopped

    openrank-rxp:
        build:
            context: .
            dockerfile: node/Dockerfile.rxp
        container_name: openrank-rxp
        ports:
            - "8080:8080"
        networks:
            - avsnet
        env_file:
            - .env
        restart: unless-stopped
