networks:
    avsnet:
        driver: bridge

services:
    openrank-rxp:
        network_mode: host
        env_file:
            - .env
        restart: unless-stopped
        build:
            dockerfile: node/Dockerfile
    anvil:
        ports:
            - "8545:8545"
        networks:
            - avsnet
        build:
            dockerfile: anvil/Dockerfile
