[profile.default]
src = "contracts/src"
out = "contracts/out"
test = "contracts/test"
cache_path = "contracts/cache"
libs = ["contracts/lib"]
solc = "0.8.25"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
remappings = ["forge-std/=contracts/lib/forge-std/src/"]

[fmt]
bracket_spacing = false
int_types = "long"
line_length = 100
multiline_func_header = "params_first"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
