[profile.default]
src = "contracts/src"
out = "contracts/out"
test = "contracts/test"
cache_path = "contracts/cache"
libs = ["contracts/lib"]
solc = "0.8.27"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
remappings = [
    "@eigenlayer/=contracts/lib/eigenlayer-middleware/lib/eigenlayer-contracts/src/",
    "@eigenlayer-scripts/=contracts/lib/eigenlayer-middleware/lib/eigenlayer-contracts/script/",
    "@eigenlayer-middleware/=contracts/lib/eigenlayer-middleware/",
    "@openzeppelin/=contracts/lib/eigenlayer-middleware/lib/openzeppelin-contracts/",
    "@openzeppelin-upgrades/=contracts/lib/eigenlayer-middleware/lib/openzeppelin-contracts-upgradeable/",
    "forge-std/=contracts/lib/eigenlayer-middleware/lib/forge-std/src/",
]

[fmt]
bracket_spacing = false
int_types = "long"
line_length = 100
multiline_func_header = "params_first"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
