[profile.default]
src = "contracts/src"
out = "contracts/out"
test = "contracts/test"
cache_path = "contracts/cache"
libs = ["contracts/lib"]
fs_permissions = [{ access = "read-write", path = "./" }]
solc = "0.8.27"
via-ir = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
remappings = [
    "@openzeppelin/=contracts/lib/rxp/contracts/lib/eigenda/contracts/lib/openzeppelin-contracts/",
    "@openzeppelin-upgrades/=contracts/lib/rxp/contracts/lib/eigenda/contracts/lib/openzeppelin-contracts-upgradeable/",
    "eigenda/=contracts/lib/rxp/contracts/lib/eigenda/",
    "eigenlayer-middleware/=contracts/lib/rxp/contracts/lib/eigenda/contracts/lib/eigenlayer-middleware/",
    "eigenlayer-contracts/=contracts/lib/rxp/contracts/lib/eigenda/contracts/lib/eigenlayer-middleware/lib/eigenlayer-contracts/",
    "teal-contracts/=contracts/lib/rxp/contracts/lib/teal/example/contracts/",
    "forge-std/=contracts/lib/rxp/contracts/lib/forge-std/src/",
    "ds-test/=contracts/lib/rxp/contracts/lib/forge-std/lib/ds-test/src/",
]

[fmt]
bracket_spacing = false
int_types = "long"
line_length = 100
multiline_func_header = "params_first"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
